// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace Models
{
    public partial class Company
    {
        public int CompanyId { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public byte[] Logo { get; set; }

        public string Description { get; set; }

        public int ManagerId { get; set; }

        public virtual ICollection<Employer> Employers { get; set; } = new List<Employer>();

        public virtual Employer Manager { get; set; }

        public virtual ICollection<Vacancy> Vacancies { get; set; } = new List<Vacancy>();
    }
}
