// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models
{
    public partial class Employer
    {
        public int UserId { get; set; }

        public int? CompanyId { get; set; }

        public virtual Company Company { get; set; }

        public virtual Company CompanyNavigation { get; set; }

        public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

        public virtual User User { get; set; }

        public virtual ICollection<Vacancy> Vacancies { get; set; } = new List<Vacancy>();
    }
}
