// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models
{
    public partial class JobApplication
    {
        public int AppId { get; set; }

        public DateTime? AppDate { get; set; }

        public int JobseekerId { get; set; }

        public int VacancyId { get; set; }

        public int EmployerId { get; set; }

        public string Status { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual JobSeeker Jobseeker { get; set; }

        public virtual Vacancy Vacancy { get; set; }
    }
}
