// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;


namespace Models
{
    public partial class User
    {
        public int UserId { get; set; }

        public string Name { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public string Phone { get; set; }

        public DateTime? BirthDate { get; set; }

        public DateTime? SignupDate { get; set; }

        public string UserType { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual JobSeeker JobSeeker { get; set; }
    }
}
