// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models
{
    public partial class Vacancy
    {
        public int VacancyId { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Skills { get; set; }

        public string Status { get; set; }

        public string ExperienceLevel { get; set; }

        public string WorkMode { get; set; }

        public string JobType { get; set; }

        public DateTime? Deadline { get; set; }

        public DateTime? PostDate { get; set; }

        public int CompanyId { get; set; }

        public int EmployerId { get; set; }

        public virtual Company Company { get; set; }

        public virtual Employer Employer { get; set; }

        public virtual ICollection<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

        public virtual ICollection<SavedJob> SavedJobs { get; set; } = new List<SavedJob>();
    }
}
